name: Test GeoLocator
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # or specify a specific version like '3.9'
      # Create and activate virtual environment
      - name: Create virtual environment
        run: python3 -m venv .venv
      # Activate virtual environment and install dependencies
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
      # Run the test script
      - name: Run test script
        run: |
          source .venv/bin/activate
          python3 -m unittest test_geoloc_util.py